BG_DARK_BLUE = (0, 0.129, 0.278)
BG_LIGHT_BLUE = (0.675, 0.859, 1)
WHITE_COLOR = (1,1,1)
GREY_COLOR = (0.2,0.2,0.2)

CURRENT_PATH = [None, None, None]
CURRENT_EVENT = None

LANGUAGE_TO_ADD = CATEGORY_TO_ADD = CONTENT_TO_ADD = ''
LANGUAGE_TO_DEL = CATEGORY_TO_DEL = CONTENT_TO_DEL = ''